---
- name: Basic box with phalcon 3.1 / php 7.1 setup
  hosts: dev
  become: true

  vars:
    templates:
      common: dev

  roles:
    - common
    - sshd
    - php
    - nginx
    - phalcon
    - database

